### On tag

on:
  push:
    tags:
      - '*/test/*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: testing
    steps:
      - name: Split tag name
        id: split
        run: |
          last=(${${GITHUB_REF_NAME##*/}//-build/})
          echo "::set-output name=ref::$last"
      - name: Test variable
        run: |
          echo ${{ steps.split.outputs.ref }}
