### On tag

on:
  push:
    tags:
      - '*/test/*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: testing
    steps:
      - name: Split tag name
        id: split
        run: |
          last=${GITHUB_REF_NAME##*/}
          cleaned=${$last//-build/}
          echo "ref=$cleaned" >> "$GITHUB_OUTPUT"
      - name: Test variable
        run: |
          echo ${{ steps.split.outputs.ref }}
